ciudad:
    path:     /
    defaults: { _controller: "ModulosPersonasBundle:Ciudad:index" }

ciudad_show:
    path:     /{id}/show
    defaults: { _controller: "ModulosPersonasBundle:Ciudad:show" }

ciudad_new:
    path:     /new
    defaults: { _controller: "ModulosPersonasBundle:Ciudad:new" }

ciudad_create:
    path:     /create
    defaults: { _controller: "ModulosPersonasBundle:Ciudad:create" }
    methods:  POST

ciudad_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModulosPersonasBundle:Ciudad:edit" }

ciudad_update:
    path:     /{id}/update
    defaults: { _controller: "ModulosPersonasBundle:Ciudad:update" }
    methods:  [POST, PUT]

ciudad_delete:
    path:     /{id}/delete
    defaults: { _controller: "ModulosPersonasBundle:Ciudad:delete" }
    methods:  [POST, DELETE]
