estadodocumento:
    path:     /
    defaults: { _controller: "ModulosPersonasBundle:EstadoDocumento:index" }

estadodocumento_show:
    path:     /{id}/show
    defaults: { _controller: "ModulosPersonasBundle:EstadoDocumento:show" }

estadodocumento_new:
    path:     /new
    defaults: { _controller: "ModulosPersonasBundle:EstadoDocumento:new" }

estadodocumento_create:
    path:     /create
    defaults: { _controller: "ModulosPersonasBundle:EstadoDocumento:create" }


estadodocumento_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModulosPersonasBundle:EstadoDocumento:edit" }

estadodocumento_update:
    path:     /{id}/update
    defaults: { _controller: "ModulosPersonasBundle:EstadoDocumento:update" }
    methods:  [POST, PUT]

estadodocumento_delete:
    path:     /delete/{id}
    defaults: { _controller: "ModulosPersonasBundle:EstadoDocumento:delete",id:""}
    
