operador:
    path:     /
    defaults: { _controller: "ModulosPersonasBundle:Operador:index" }

operador_show:
    path:     /{id}/show
    defaults: { _controller: "ModulosPersonasBundle:Operador:show" }

operador_new:
    path:     /new
    defaults: { _controller: "ModulosPersonasBundle:Operador:new" }

operador_create:
    path:     /create
    defaults: { _controller: "ModulosPersonasBundle:Operador:create" }
    methods:  POST

operador_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModulosPersonasBundle:Operador:edit" }

operador_update:
    path:     /{id}/update
    defaults: { _controller: "ModulosPersonasBundle:Operador:update" }
    methods:  [POST, PUT]

operador_delete:
    path:     /{id}/delete
    defaults: { _controller: "ModulosPersonasBundle:Operador:delete" }
    methods:  [POST, DELETE]
