productocontablecuenta:
    path:     /
    defaults: { _controller: "ModulosPersonasBundle:ProductoContableCuenta:index" }

productocontablecuenta_show:
    path:     /{id}/show
    defaults: { _controller: "ModulosPersonasBundle:ProductoContableCuenta:show" }

productocontablecuenta_new:
    path:     /new
    defaults: { _controller: "ModulosPersonasBundle:ProductoContableCuenta:new" }

productocontablecuenta_create:
    path:     /create
    defaults: { _controller: "ModulosPersonasBundle:ProductoContableCuenta:create" }
    methods:  POST

productocontablecuenta_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModulosPersonasBundle:ProductoContableCuenta:edit" }

productocontablecuenta_update:
    path:     /{id}/update
    defaults: { _controller: "ModulosPersonasBundle:ProductoContableCuenta:update" }
    methods:  [POST, PUT]

productocontablecuenta_delete:
    path:     /{id}/delete
    defaults: { _controller: "ModulosPersonasBundle:ProductoContableCuenta:delete" }
    methods:  [POST, DELETE]
