tipoahorro:
    path:     /
    defaults: { _controller: "ModulosPersonasBundle:TipoAhorro:index" }

tipoahorro_show:
    path:     /{id}/show
    defaults: { _controller: "ModulosPersonasBundle:TipoAhorro:show" }

tipoahorro_new:
    path:     /new
    defaults: { _controller: "ModulosPersonasBundle:TipoAhorro:new" }

tipoahorro_create:
    path:     /create
    defaults: { _controller: "ModulosPersonasBundle:TipoAhorro:create" }
    

tipoahorro_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModulosPersonasBundle:TipoAhorro:edit" }

tipoahorro_update:
    path:     /{id}/update
    defaults: { _controller: "ModulosPersonasBundle:TipoAhorro:update" }
    

tipoahorro_delete:
    path:     /delete/{id}
    defaults: { _controller: "ModulosPersonasBundle:TipoAhorro:delete",id:""}
   
